name: my first pipline

on:
  push:
    branch:
      - main 

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: host name
    run:  Hostname
  - name: Uname
    run: Uname 
  - name: storage
    run:  Free -h
  - name: Df
    run:  Df -h
  - name: time
    run:  Uptime
     
