name: my first pipline

on:
  push:
    branch:
      - main 

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: host name
    run:  Hostname
  - name: storage
    uses: Free -h 
  - name: uname
    run:  Uname
  - name: Df
    run:  Df -h
  - name: time
    run:  Uptime
     
