name: my first pipline

on:
  push:
    branches:
      - main 

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: host name
    run:  hostname
  - name: Uname
    run:  uname 
  - name: storage
    run:  free -h
  - name: Df
    run:  Df -h
  - name: time
    run:  uptime
     
